apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-hostpath-pv-for-mysql
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/mysql
  storageClassName: static-pv-hostpath # To make it matchable for pvc that wants to request volume from this pv, we use this field as a label to create linkage.
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - multi-node-lab-m02
