apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-from-static-pv-for-mysql
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: static-pv-hostpath
  accessModes:
    - ReadWriteOnce
