apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jack-nfs-storage
provisioner: kubernetes.io/no-provisioner # Indicates manual PV management
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
