apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jack-static-nfs-pvc
spec:
  storageClassName: jack-nfs-storage # it's used to match the PV defined in step 01.
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi # Can be <= PV capacity
