apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jack-pvc-for-static-local-pv
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: jack-local-storage
  accessModes:
    - ReadWriteOnce
