apiVersion: apps/v1
kind: Deployment
metadata:
  name: jack-mysql-deployment
spec:
  selector:
    matchLabels:
      app: jack-mysql
  template:
    metadata:
      labels:
        app: jack-mysql
    spec:
      containers:
        - name: jack-mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: jack-pvc-for-static-local-pv
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - multi-node-lab-m02
